language: objective-c
osx_image: xcode7.1
before_install: true
install: true
script: script/cibuild Concurrent Concurrent-iOS
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
